// File: top.v
// Generated by MyHDL 0.9.0
// Date: Sun Jun 25 16:13:15 2017


`timescale 1ns/10ps

module top (
    clk,
    rst,
    g_input,
    e_input,
    o
);


input [0:0] clk;
input [0:0] rst;
input [2:0] g_input;
input [2:0] e_input;
output [1:0] o;
reg [1:0] o;

reg [0:0] OUT_win;





always @(e_input, g_input) begin: TOP_WIN_INSTANCE_LOGIC
    if (((g_input == 0) && ((e_input == 2) || (e_input == 4)))) begin
        OUT_win = 1;
    end
    else begin
        if (((g_input == 1) && ((e_input == 0) || (e_input == 3)))) begin
            OUT_win = 1;
        end
        else begin
            if (((g_input == 2) && ((e_input == 1) || (e_input == 4)))) begin
                OUT_win = 1;
            end
            else begin
                if (((g_input == 3) && ((e_input == 2) || (e_input == 0)))) begin
                    OUT_win = 1;
                end
                else begin
                    if (((g_input == 4) && ((e_input == 1) || (e_input == 3)))) begin
                        OUT_win = 1;
                    end
                    else begin
                        OUT_win = 0;
                    end
                end
            end
        end
    end
end


always @(e_input, OUT_win, g_input) begin: TOP_RPSSL_INSTANCE_LOGIC
    if ((g_input > 4)) begin
        o = 2;
    end
    else if ((e_input > 4)) begin
        o = 2;
    end
    else if ((g_input == e_input)) begin
        o = 0;
    end
    else if (OUT_win) begin
        o = 1;
    end
    else begin
        o = 3;
    end
end

endmodule
